name: "Stock Price Notifier"

on: 
  schedule:
    - cron: '0 6 * * *'  # testing trigger time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out repository content"
        uses: actions/checkout@v3

      - name: "Setting up Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: "Installing Python Modules/Packages"
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Running Python Script"  
        env:
          ACCOUNT_SID: ${{secrets.ACCOUNT_SID}}
          AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
          FROM: ${{secrets.FROM}}
          TO: ${{secrets.TO}}
        run: python main.py
